export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const ADD_FAILURE = 'ADD_FAILURE';

export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_FAILURE = 'EDIT_FAILURE';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

export const FIND_REQUEST = 'FIND_REQUEST';
export const FIND_SUCCESS = 'FIND_SUCCESS';
export const FIND_FAILURE = 'FIND_FAILURE';

export const FINDS_REQUEST = 'FINDS_REQUEST';
export const FINDS_SUCCESS = 'FINDS_SUCCESS';
export const FINDS_FAILURE = 'FINDS_FAILURE';
